import { parseTableManifest, type TableManifest } from "./manifest";

/**
 * Freezing a manifest into the app at build time.
 *
 * Fetching the manifest at runtime is one round trip before the table can draw
 * anything. A snapshot removes it: check the endpoint's answer into the repo,
 * pass it as `initialManifest`, and the first paint has a schema while the
 * query revalidates behind it.
 *
 * The trade is explicit rather than hidden. A snapshot is a copy, so it goes
 * stale when the endpoint changes — which is exactly why `useTableManifest`
 * still revalidates instead of trusting it forever, and why the generated file
 * records where and when it came from.
 */

export type SnapshotOptions = {
  /** The URL it came from, recorded in the header comment. */
  source?: string;
  /** Name of the exported const. Defaults to `manifest`. */
  exportName?: string;
  /**
   * Import specifier for the `TableManifest` type. Defaults to the registry
   * path; set it to wherever the schema block landed in the consuming app
   * (`@/lib/table-schema`, most likely).
   */
  typeImport?: string;
  /**
   * Timestamp for the header comment. Injectable so the output is
   * deterministic in tests, and so a build can stamp its own commit time.
   */
  generatedAt?: Date | string;
};

const DEFAULT_TYPE_IMPORT = "@dtf/registry/lib/table-schema";

/** A JS identifier, so the generated module actually parses. */
function assertIdentifier(name: string): void {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) {
    throw new Error(
      `exportName ${JSON.stringify(name)} is not a valid identifier`,
    );
  }
}

/**
 * Render a manifest as a TypeScript module.
 *
 * The manifest is re-parsed on the way in: a snapshot is generated from a live
 * endpoint's response, so it goes through the same validation as one consumed
 * at runtime. Freezing an invalid manifest into the repo would only move the
 * failure to a place where nobody is looking for it.
 */
export function manifestToModule(
  manifest: unknown,
  options?: SnapshotOptions,
): string {
  const exportName = options?.exportName ?? "manifest";
  assertIdentifier(exportName);

  const parsed: TableManifest = parseTableManifest(manifest);
  const typeImport = options?.typeImport ?? DEFAULT_TYPE_IMPORT;
  const generatedAt =
    options?.generatedAt instanceof Date
      ? options.generatedAt.toISOString()
      : options?.generatedAt;

  const provenance = [
    " * Generated by `manifestToModule`. Do not edit by hand.",
    options?.source ? ` * Source: ${options.source}` : null,
    generatedAt ? ` * Generated: ${generatedAt}` : null,
    " *",
    " * This is a snapshot. The table still revalidates it at runtime, so an",
    " * endpoint whose schema has moved on will correct itself — but regenerate",
    " * this file when that happens, or every first paint starts from stale",
    " * columns.",
  ].filter((line): line is string => line !== null);

  return [
    "/**",
    ...provenance,
    " */",
    "",
    // Built with `JSON.stringify` rather than an interpolated string literal:
    // it escapes the specifier properly, and it keeps this line from reading as
    // a real import to any tool that scans this file's own imports.
    `import type { TableManifest } from ${JSON.stringify(typeImport)};`,
    "",
    `export const ${exportName}: TableManifest = ${JSON.stringify(parsed, null, 2)};`,
    "",
  ].join("\n");
}

/**
 * Fetch a manifest and render it as a module, ready to write to disk.
 *
 * The whole `dtf pull` step, minus the file write — which is left to the
 * caller so this stays runtime-agnostic and needs no filesystem access.
 *
 * @example
 * ```ts
 * // scripts/pull-manifest.ts
 * import { writeFileSync } from "node:fs";
 * import { pullManifestModule } from "@dtf/registry/lib/table-schema";
 *
 * const url = "https://api.example.com/logs/schema";
 * writeFileSync("src/app/logs/manifest.ts", await pullManifestModule(url));
 * ```
 */
export async function pullManifestModule(
  url: string,
  options?: SnapshotOptions & {
    headers?: HeadersInit;
    fetch?: typeof fetch;
  },
): Promise<string> {
  const doFetch = options?.fetch ?? fetch;
  const response = await doFetch(url, { headers: options?.headers });
  if (!response.ok) {
    throw new Error(
      `Could not pull the manifest from ${url}: ${response.status} ${response.statusText}`.trim(),
    );
  }
  return manifestToModule(await response.json(), {
    source: url,
    generatedAt: new Date(),
    ...options,
  });
}
