export type ExampleDataset = {
  label: string;
  data: Record<string, unknown>[];
};

export const EXAMPLE_DATASETS: ExampleDataset[] = [
  {
    label: "Employees",
    data: [
      {
        name: "Alice Johnson",
        age: 30,
        department: "Engineering",
        salary: 95000,
        active: true,
        score: 88,
      },
      {
        name: "Bob Martinez",
        age: 25,
        department: "Design",
        salary: 72000,
        active: false,
        score: 74,
      },
      {
        name: "Charlie Lee",
        age: 35,
        department: "Engineering",
        salary: 110000,
        active: true,
        score: 92,
      },
      {
        name: "Diana Patel",
        age: 28,
        department: "Marketing",
        salary: 68000,
        active: true,
        score: 81,
      },
      {
        name: "Ethan Kim",
        age: 42,
        department: "Management",
        salary: 145000,
        active: true,
        score: 95,
      },
      {
        name: "Fiona Chen",
        age: 31,
        department: "Engineering",
        salary: 98000,
        active: true,
        score: 87,
      },
      {
        name: "George Okafor",
        age: 27,
        department: "Sales",
        salary: 61000,
        active: false,
        score: 65,
      },
      {
        name: "Hannah Müller",
        age: 33,
        department: "HR",
        salary: 71000,
        active: true,
        score: 78,
      },
      {
        name: "Ivan Petrov",
        age: 38,
        department: "Engineering",
        salary: 120000,
        active: true,
        score: 90,
      },
      {
        name: "Julia Santos",
        age: 24,
        department: "Design",
        salary: 65000,
        active: true,
        score: 72,
      },
      {
        name: "Kevin Nguyen",
        age: 45,
        department: "Management",
        salary: 155000,
        active: false,
        score: 91,
      },
      {
        name: "Laura Beck",
        age: 29,
        department: "Marketing",
        salary: 70000,
        active: true,
        score: 83,
      },
      {
        name: "Marcus Hill",
        age: 36,
        department: "Sales",
        salary: 78000,
        active: true,
        score: 77,
      },
      {
        name: "Nina Johansson",
        age: 32,
        department: "Engineering",
        salary: 105000,
        active: true,
        score: 89,
      },
      {
        name: "Oscar Tremblay",
        age: 40,
        department: "Finance",
        salary: 130000,
        active: false,
        score: 84,
      },
      {
        name: "Priya Sharma",
        age: 26,
        department: "Engineering",
        salary: 88000,
        active: true,
        score: 86,
      },
      {
        name: "Quinn Adeyemi",
        age: 34,
        department: "HR",
        salary: 74000,
        active: true,
        score: 79,
      },
      {
        name: "Rachel Wong",
        age: 39,
        department: "Finance",
        salary: 125000,
        active: true,
        score: 93,
      },
      {
        name: "Sam Torres",
        age: 23,
        department: "Design",
        salary: 58000,
        active: false,
        score: 68,
      },
      {
        name: "Tina Eriksson",
        age: 44,
        department: "Management",
        salary: 148000,
        active: true,
        score: 94,
      },
    ],
  },
  {
    label: "HTTP Logs",
    data: [
      {
        timestamp: "2024-03-01T08:12:34.000Z",
        method: "GET",
        path: "/api/users",
        status: 200,
        latency: 38,
        region: "us-east-1",
      },
      {
        timestamp: "2024-03-01T08:14:02.000Z",
        method: "POST",
        path: "/api/auth/login",
        status: 201,
        latency: 112,
        region: "us-east-1",
      },
      {
        timestamp: "2024-03-01T08:15:50.000Z",
        method: "GET",
        path: "/api/orders",
        status: 200,
        latency: 55,
        region: "eu-west-1",
      },
      {
        timestamp: "2024-03-01T08:18:11.000Z",
        method: "DELETE",
        path: "/api/users/42",
        status: 204,
        latency: 23,
        region: "us-west-2",
      },
      {
        timestamp: "2024-03-01T08:22:07.000Z",
        method: "GET",
        path: "/api/products",
        status: 200,
        latency: 44,
        region: "ap-southeast-1",
      },
      {
        timestamp: "2024-03-01T08:25:33.000Z",
        method: "PUT",
        path: "/api/users/17",
        status: 200,
        latency: 87,
        region: "us-east-1",
      },
      {
        timestamp: "2024-03-01T08:31:19.000Z",
        method: "POST",
        path: "/api/orders",
        status: 400,
        latency: 19,
        region: "eu-west-1",
      },
      {
        timestamp: "2024-03-01T08:34:45.000Z",
        method: "GET",
        path: "/api/users/99",
        status: 404,
        latency: 11,
        region: "us-east-1",
      },
      {
        timestamp: "2024-03-01T08:40:22.000Z",
        method: "GET",
        path: "/health",
        status: 200,
        latency: 4,
        region: "us-west-2",
      },
      {
        timestamp: "2024-03-01T08:45:58.000Z",
        method: "POST",
        path: "/api/payments",
        status: 500,
        latency: 3201,
        region: "us-east-1",
      },
      {
        timestamp: "2024-03-01T09:02:14.000Z",
        method: "GET",
        path: "/api/dashboard",
        status: 200,
        latency: 131,
        region: "eu-west-1",
      },
      {
        timestamp: "2024-03-01T09:08:37.000Z",
        method: "PUT",
        path: "/api/orders/88",
        status: 200,
        latency: 74,
        region: "ap-southeast-1",
      },
      {
        timestamp: "2024-03-01T09:14:05.000Z",
        method: "GET",
        path: "/api/reports",
        status: 401,
        latency: 8,
        region: "us-east-1",
      },
      {
        timestamp: "2024-03-01T09:21:49.000Z",
        method: "POST",
        path: "/api/notifications",
        status: 201,
        latency: 56,
        region: "us-west-2",
      },
      {
        timestamp: "2024-03-01T09:30:00.000Z",
        method: "DELETE",
        path: "/api/sessions/abc",
        status: 204,
        latency: 17,
        region: "eu-west-1",
      },
      {
        timestamp: "2024-03-01T09:38:22.000Z",
        method: "GET",
        path: "/api/analytics",
        status: 200,
        latency: 289,
        region: "us-east-1",
      },
      {
        timestamp: "2024-03-01T09:45:11.000Z",
        method: "POST",
        path: "/api/uploads",
        status: 503,
        latency: 5012,
        region: "ap-southeast-1",
      },
      {
        timestamp: "2024-03-01T09:52:44.000Z",
        method: "GET",
        path: "/api/users",
        status: 200,
        latency: 42,
        region: "eu-west-1",
      },
    ],
  },
  {
    label: "Notes",
    data: [
      {
        title: "Q2 Roadmap Draft",
        content: "Cover infrastructure migration and new onboarding flow.",
        category: "work",
        tags: ["planning", "important"],
        pinned: true,
        created_at: "2024-02-10T09:00:00.000Z",
      },
      {
        title: "Book Recommendations",
        content: "Thinking Fast and Slow, SICP, The Pragmatic Programmer.",
        category: "personal",
        tags: ["books", "learning"],
        pinned: false,
        created_at: "2024-02-11T14:30:00.000Z",
      },
      {
        title: "Grocery List",
        content: "Eggs, oat milk, sourdough, apples, olive oil.",
        category: "personal",
        tags: ["todo"],
        pinned: false,
        created_at: "2024-02-12T07:15:00.000Z",
      },
      {
        title: "API Design Notes",
        content: "Prefer resource-based URLs, use consistent pagination.",
        category: "work",
        tags: ["engineering", "important"],
        pinned: true,
        created_at: "2024-02-13T11:20:00.000Z",
      },
      {
        title: "Morning Routine Ideas",
        content: "5 min stretch, cold shower, 10 min journal.",
        category: "health",
        tags: ["habits"],
        pinned: false,
        created_at: "2024-02-14T06:45:00.000Z",
      },
      {
        title: "Conference Talk Outline",
        content: "Intro, problem statement, live demo, Q&A.",
        category: "work",
        tags: ["speaking", "planning"],
        pinned: true,
        created_at: "2024-02-15T16:00:00.000Z",
      },
      {
        title: "Investment Notes",
        content: "Review index fund allocation. Consider rebalancing.",
        category: "finance",
        tags: ["important"],
        pinned: false,
        created_at: "2024-02-16T20:10:00.000Z",
      },
      {
        title: "React 19 Features",
        content: "Server actions, use() hook, improved transitions.",
        category: "study",
        tags: ["engineering", "learning"],
        pinned: false,
        created_at: "2024-02-17T13:05:00.000Z",
      },
      {
        title: "Team Retrospective",
        content: "Went well: CI speed. Improve: PR review turnaround.",
        category: "work",
        tags: ["planning"],
        pinned: false,
        created_at: "2024-02-18T17:30:00.000Z",
      },
      {
        title: "Travel Packing List",
        content: "Passport, adapter, camera, noise-cancelling headphones.",
        category: "personal",
        tags: ["todo"],
        pinned: true,
        created_at: "2024-02-19T08:00:00.000Z",
      },
      {
        title: "Side Project Ideas",
        content: "CLI for time-tracking, local-first notes app.",
        category: "work",
        tags: ["engineering", "planning"],
        pinned: false,
        created_at: "2024-02-20T22:00:00.000Z",
      },
      {
        title: "Database Optimization",
        content: "Add index on user_id + created_at, analyze slow queries.",
        category: "work",
        tags: ["engineering", "important"],
        pinned: true,
        created_at: "2024-02-21T10:45:00.000Z",
      },
      {
        title: "Weekly Goals",
        content: "Finish report, exercise 3x, call parents.",
        category: "personal",
        tags: ["habits", "todo"],
        pinned: false,
        created_at: "2024-02-22T07:00:00.000Z",
      },
      {
        title: "Tax Documents Checklist",
        content: "W-2, 1099-B, mortgage interest statement.",
        category: "finance",
        tags: ["important", "todo"],
        pinned: true,
        created_at: "2024-02-23T12:00:00.000Z",
      },
      {
        title: "Podcast Queue",
        content: "Lex Fridman #400, Huberman on sleep, 99% Invisible.",
        category: "personal",
        tags: ["learning"],
        pinned: false,
        created_at: "2024-02-24T19:30:00.000Z",
      },
    ],
  },
  {
    label: "Auction Bids",
    data: [
      {
        item: "1962 Fender Stratocaster",
        bidder: "guitar_collector",
        amount: 14500,
        currency: "USD",
        status: "active",
        reserve_met: true,
        placed_at: "2024-03-10T10:00:00.000Z",
      },
      {
        item: "Signed Pelé Jersey",
        bidder: "sports_fan_99",
        amount: 3200,
        currency: "USD",
        status: "won",
        reserve_met: true,
        placed_at: "2024-03-10T10:05:00.000Z",
      },
      {
        item: "First Edition Dune",
        bidder: "bibliophile42",
        amount: 890,
        currency: "USD",
        status: "won",
        reserve_met: true,
        placed_at: "2024-03-10T10:12:00.000Z",
      },
      {
        item: "Vintage Rolex Submariner",
        bidder: "watch_hunter",
        amount: 22000,
        currency: "EUR",
        status: "active",
        reserve_met: false,
        placed_at: "2024-03-10T10:20:00.000Z",
      },
      {
        item: "Abstract Oil Painting",
        bidder: "art_lover",
        amount: 4700,
        currency: "GBP",
        status: "lost",
        reserve_met: false,
        placed_at: "2024-03-10T10:30:00.000Z",
      },
      {
        item: "Pokémon Base Set Booster Box",
        bidder: "poke_master",
        amount: 6100,
        currency: "USD",
        status: "won",
        reserve_met: true,
        placed_at: "2024-03-10T10:45:00.000Z",
      },
      {
        item: "1970s Space Age Lamp",
        bidder: "mid_century_mod",
        amount: 310,
        currency: "EUR",
        status: "active",
        reserve_met: true,
        placed_at: "2024-03-10T11:00:00.000Z",
      },
      {
        item: "Rare Comic: Amazing Fantasy #15",
        bidder: "marvel_collector",
        amount: 48000,
        currency: "USD",
        status: "active",
        reserve_met: true,
        placed_at: "2024-03-10T11:10:00.000Z",
      },
      {
        item: "18th Century Pocket Watch",
        bidder: "antique_seeker",
        amount: 1800,
        currency: "GBP",
        status: "lost",
        reserve_met: false,
        placed_at: "2024-03-10T11:25:00.000Z",
      },
      {
        item: "Signed Bowie Vinyl LP",
        bidder: "vinyl_vault",
        amount: 2400,
        currency: "GBP",
        status: "won",
        reserve_met: true,
        placed_at: "2024-03-10T11:40:00.000Z",
      },
      {
        item: "Leica M3 Camera",
        bidder: "film_photographer",
        amount: 3100,
        currency: "EUR",
        status: "active",
        reserve_met: true,
        placed_at: "2024-03-10T12:00:00.000Z",
      },
      {
        item: "Handwoven Persian Rug",
        bidder: "interior_design",
        amount: 5600,
        currency: "USD",
        status: "cancelled",
        reserve_met: false,
        placed_at: "2024-03-10T12:15:00.000Z",
      },
      {
        item: "Apple I Computer Board",
        bidder: "tech_historian",
        amount: 375000,
        currency: "USD",
        status: "active",
        reserve_met: true,
        placed_at: "2024-03-10T12:30:00.000Z",
      },
      {
        item: "Limited Sneaker: Air Jordan OG",
        bidder: "sneakerhead",
        amount: 2900,
        currency: "USD",
        status: "lost",
        reserve_met: false,
        placed_at: "2024-03-10T12:45:00.000Z",
      },
      {
        item: "Meteorite Fragment 220g",
        bidder: "space_collector",
        amount: 1150,
        currency: "USD",
        status: "won",
        reserve_met: true,
        placed_at: "2024-03-10T13:00:00.000Z",
      },
    ],
  },
  {
    label: "Orders",
    data: [
      {
        order_id: "ORD-1001",
        product: "Mechanical Keyboard",
        category: "Electronics",
        price: 129.99,
        quantity: 1,
        status: "delivered",
        payment: "credit_card",
        ordered_at: "2024-03-01T08:00:00.000Z",
      },
      {
        order_id: "ORD-1002",
        product: "Running Shoes",
        category: "Sports",
        price: 94.5,
        quantity: 2,
        status: "shipped",
        payment: "paypal",
        ordered_at: "2024-03-02T09:15:00.000Z",
      },
      {
        order_id: "ORD-1003",
        product: "The Art of War",
        category: "Books",
        price: 12.99,
        quantity: 3,
        status: "delivered",
        payment: "apple_pay",
        ordered_at: "2024-03-02T11:30:00.000Z",
      },
      {
        order_id: "ORD-1004",
        product: "Desk Lamp",
        category: "Home",
        price: 49.99,
        quantity: 1,
        status: "processing",
        payment: "credit_card",
        ordered_at: "2024-03-03T14:00:00.000Z",
      },
      {
        order_id: "ORD-1005",
        product: "Noise-Cancelling Headphones",
        category: "Electronics",
        price: 279.0,
        quantity: 1,
        status: "delivered",
        payment: "bank_transfer",
        ordered_at: "2024-03-03T16:45:00.000Z",
      },
      {
        order_id: "ORD-1006",
        product: "Yoga Mat",
        category: "Sports",
        price: 34.95,
        quantity: 1,
        status: "cancelled",
        payment: "paypal",
        ordered_at: "2024-03-04T07:20:00.000Z",
      },
      {
        order_id: "ORD-1007",
        product: "Linen Shirt",
        category: "Clothing",
        price: 59.0,
        quantity: 2,
        status: "shipped",
        payment: "credit_card",
        ordered_at: "2024-03-04T10:00:00.000Z",
      },
      {
        order_id: "ORD-1008",
        product: "Cast Iron Skillet",
        category: "Home",
        price: 44.99,
        quantity: 1,
        status: "delivered",
        payment: "apple_pay",
        ordered_at: "2024-03-05T13:10:00.000Z",
      },
      {
        order_id: "ORD-1009",
        product: "USB-C Hub",
        category: "Electronics",
        price: 39.99,
        quantity: 3,
        status: "delivered",
        payment: "credit_card",
        ordered_at: "2024-03-05T15:30:00.000Z",
      },
      {
        order_id: "ORD-1010",
        product: "Climbing Harness",
        category: "Sports",
        price: 88.0,
        quantity: 1,
        status: "pending",
        payment: "bank_transfer",
        ordered_at: "2024-03-06T08:45:00.000Z",
      },
      {
        order_id: "ORD-1011",
        product: "Wool Sweater",
        category: "Clothing",
        price: 74.5,
        quantity: 1,
        status: "shipped",
        payment: "paypal",
        ordered_at: "2024-03-06T11:00:00.000Z",
      },
      {
        order_id: "ORD-1012",
        product: "Dune Omnibus",
        category: "Books",
        price: 28.99,
        quantity: 2,
        status: "delivered",
        payment: "apple_pay",
        ordered_at: "2024-03-07T09:00:00.000Z",
      },
      {
        order_id: "ORD-1013",
        product: "Standing Desk Mat",
        category: "Home",
        price: 55.0,
        quantity: 1,
        status: "processing",
        payment: "credit_card",
        ordered_at: "2024-03-07T14:20:00.000Z",
      },
      {
        order_id: "ORD-1014",
        product: "Wireless Charger",
        category: "Electronics",
        price: 29.99,
        quantity: 4,
        status: "delivered",
        payment: "credit_card",
        ordered_at: "2024-03-08T07:30:00.000Z",
      },
      {
        order_id: "ORD-1015",
        product: "Trail Running Vest",
        category: "Sports",
        price: 110.0,
        quantity: 1,
        status: "cancelled",
        payment: "paypal",
        ordered_at: "2024-03-08T12:00:00.000Z",
      },
    ],
  },
  {
    label: "Issues",
    data: [
      {
        title: "Login fails with SSO on Safari",
        priority: "critical",
        status: "in_progress",
        assignee: "Alice Chen",
        labels: ["bug", "auth"],
        points: 8,
        created_at: "2024-03-01T09:00:00.000Z",
      },
      {
        title: "Add dark mode support",
        priority: "medium",
        status: "open",
        assignee: "Bob Smith",
        labels: ["feature", "ux"],
        points: 13,
        created_at: "2024-03-02T10:30:00.000Z",
      },
      {
        title: "API rate limiting",
        priority: "high",
        status: "in_review",
        assignee: "Clara Diaz",
        labels: ["security", "performance"],
        points: 8,
        created_at: "2024-03-02T14:00:00.000Z",
      },
      {
        title: "Update README for v2",
        priority: "low",
        status: "closed",
        assignee: "David Park",
        labels: ["docs"],
        points: 2,
        created_at: "2024-03-03T08:00:00.000Z",
      },
      {
        title: "Memory leak in data fetcher",
        priority: "critical",
        status: "in_progress",
        assignee: "Alice Chen",
        labels: ["bug", "performance"],
        points: 13,
        created_at: "2024-03-03T11:15:00.000Z",
      },
      {
        title: "Export to CSV",
        priority: "medium",
        status: "open",
        assignee: "Eva Müller",
        labels: ["feature"],
        points: 5,
        created_at: "2024-03-04T09:30:00.000Z",
      },
      {
        title: "Improve table pagination",
        priority: "low",
        status: "in_progress",
        assignee: "Bob Smith",
        labels: ["ux"],
        points: 3,
        created_at: "2024-03-04T13:00:00.000Z",
      },
      {
        title: "SQL injection in search param",
        priority: "critical",
        status: "closed",
        assignee: "Clara Diaz",
        labels: ["bug", "security"],
        points: 8,
        created_at: "2024-03-05T07:45:00.000Z",
      },
      {
        title: "Onboarding email sequence",
        priority: "medium",
        status: "open",
        assignee: "David Park",
        labels: ["feature"],
        points: 5,
        created_at: "2024-03-05T14:00:00.000Z",
      },
      {
        title: "Flaky test in CI pipeline",
        priority: "high",
        status: "in_review",
        assignee: "Alice Chen",
        labels: ["bug", "docs"],
        points: 3,
        created_at: "2024-03-06T09:00:00.000Z",
      },
      {
        title: "Keyboard navigation for modals",
        priority: "medium",
        status: "open",
        assignee: "Eva Müller",
        labels: ["ux", "feature"],
        points: 5,
        created_at: "2024-03-06T11:30:00.000Z",
      },
      {
        title: "Add Prometheus metrics",
        priority: "high",
        status: "in_progress",
        assignee: "Clara Diaz",
        labels: ["feature", "performance"],
        points: 8,
        created_at: "2024-03-07T10:00:00.000Z",
      },
      {
        title: "404 page redesign",
        priority: "low",
        status: "closed",
        assignee: "Bob Smith",
        labels: ["ux"],
        points: 2,
        created_at: "2024-03-07T14:30:00.000Z",
      },
      {
        title: "Session timeout handling",
        priority: "high",
        status: "open",
        assignee: "David Park",
        labels: ["auth", "bug"],
        points: 5,
        created_at: "2024-03-08T08:00:00.000Z",
      },
      {
        title: "Localization support (i18n)",
        priority: "medium",
        status: "in_progress",
        assignee: "Eva Müller",
        labels: ["feature"],
        points: 13,
        created_at: "2024-03-08T13:00:00.000Z",
      },
    ],
  },
  {
    label: "Movies",
    data: [
      {
        title: "Inception",
        genre: "Sci-Fi",
        rating: 8.8,
        year: 2010,
        runtime: 148,
        country: "USA",
        watched: true,
      },
      {
        title: "Parasite",
        genre: "Thriller",
        rating: 8.5,
        year: 2019,
        runtime: 132,
        country: "South Korea",
        watched: true,
      },
      {
        title: "The Grand Budapest Hotel",
        genre: "Comedy",
        rating: 8.1,
        year: 2014,
        runtime: 99,
        country: "Germany",
        watched: false,
      },
      {
        title: "Interstellar",
        genre: "Sci-Fi",
        rating: 8.6,
        year: 2014,
        runtime: 169,
        country: "USA",
        watched: true,
      },
      {
        title: "Amélie",
        genre: "Romance",
        rating: 8.3,
        year: 2001,
        runtime: 122,
        country: "France",
        watched: false,
      },
      {
        title: "The Dark Knight",
        genre: "Action",
        rating: 9.0,
        year: 2008,
        runtime: 152,
        country: "USA",
        watched: true,
      },
      {
        title: "Portrait of a Lady on Fire",
        genre: "Drama",
        rating: 8.1,
        year: 2019,
        runtime: 122,
        country: "France",
        watched: false,
      },
      {
        title: "Spirited Away",
        genre: "Animation",
        rating: 8.6,
        year: 2001,
        runtime: 125,
        country: "Japan",
        watched: true,
      },
      {
        title: "Oldboy",
        genre: "Thriller",
        rating: 8.4,
        year: 2003,
        runtime: 120,
        country: "South Korea",
        watched: false,
      },
      {
        title: "Everything Everywhere All at Once",
        genre: "Sci-Fi",
        rating: 7.8,
        year: 2022,
        runtime: 139,
        country: "USA",
        watched: true,
      },
      {
        title: "The Lives of Others",
        genre: "Drama",
        rating: 8.4,
        year: 2006,
        runtime: 137,
        country: "Germany",
        watched: false,
      },
      {
        title: "Blade Runner 2049",
        genre: "Sci-Fi",
        rating: 8.0,
        year: 2017,
        runtime: 164,
        country: "USA",
        watched: true,
      },
      {
        title: "3 Idiots",
        genre: "Comedy",
        rating: 8.4,
        year: 2009,
        runtime: 170,
        country: "India",
        watched: false,
      },
      {
        title: "Mad Max: Fury Road",
        genre: "Action",
        rating: 8.1,
        year: 2015,
        runtime: 120,
        country: "Australia",
        watched: true,
      },
      {
        title: "Past Lives",
        genre: "Romance",
        rating: 7.8,
        year: 2023,
        runtime: 106,
        country: "USA",
        watched: false,
      },
    ],
  },
  {
    label: "Locations",
    data: [
      {
        name: "Eiffel Tower",
        city: "Paris",
        country: "France",
        type: "landmark",
        latitude: 48.8584,
        longitude: 2.2945,
        verified: true,
      },
      {
        name: "Sukiyabashi Jiro",
        city: "Tokyo",
        country: "Japan",
        type: "restaurant",
        latitude: 35.6752,
        longitude: 139.7635,
        verified: true,
      },
      {
        name: "The British Museum",
        city: "London",
        country: "UK",
        type: "museum",
        latitude: 51.5194,
        longitude: -0.127,
        verified: true,
      },
      {
        name: "Bondi Beach",
        city: "Sydney",
        country: "Australia",
        type: "beach",
        latitude: -33.8908,
        longitude: 151.2743,
        verified: true,
      },
      {
        name: "Central Park",
        city: "New York",
        country: "USA",
        type: "park",
        latitude: 40.7851,
        longitude: -73.9683,
        verified: true,
      },
      {
        name: "Ristorante Noma",
        city: "Copenhagen",
        country: "Denmark",
        type: "restaurant",
        latitude: 55.6867,
        longitude: 12.61,
        verified: false,
      },
      {
        name: "Colosseum",
        city: "Rome",
        country: "Italy",
        type: "landmark",
        latitude: 41.8902,
        longitude: 12.4922,
        verified: true,
      },
      {
        name: "Louvre Museum",
        city: "Paris",
        country: "France",
        type: "museum",
        latitude: 48.8606,
        longitude: 2.3376,
        verified: true,
      },
      {
        name: "Banff National Park",
        city: "Banff",
        country: "Canada",
        type: "park",
        latitude: 51.4968,
        longitude: -115.9281,
        verified: true,
      },
      {
        name: "Negresco Hotel",
        city: "Nice",
        country: "France",
        type: "hotel",
        latitude: 43.6944,
        longitude: 7.2633,
        verified: false,
      },
      {
        name: "Sagrada Família",
        city: "Barcelona",
        country: "Spain",
        type: "landmark",
        latitude: 41.4036,
        longitude: 2.1744,
        verified: true,
      },
      {
        name: "Nobu Tokyo",
        city: "Tokyo",
        country: "Japan",
        type: "restaurant",
        latitude: 35.6628,
        longitude: 139.733,
        verified: true,
      },
      {
        name: "Hyde Park",
        city: "London",
        country: "UK",
        type: "park",
        latitude: 51.5073,
        longitude: -0.1657,
        verified: true,
      },
      {
        name: "Whitehaven Beach",
        city: "Whitsundays",
        country: "Australia",
        type: "beach",
        latitude: -20.2765,
        longitude: 149.0405,
        verified: false,
      },
      {
        name: "Rijksmuseum",
        city: "Amsterdam",
        country: "Netherlands",
        type: "museum",
        latitude: 52.36,
        longitude: 4.8852,
        verified: true,
      },
    ],
  },
];

// Keep legacy exports for backwards compatibility
export interface PlaceholderRow extends Record<string, unknown> {
  name: string;
  age: number;
  department: string;
  salary: number;
  active: boolean;
  score: number;
}

export const PLACEHOLDER_DATA = EXAMPLE_DATASETS[0].data as PlaceholderRow[];
export const PLACEHOLDER_DATA_JSON = JSON.stringify(PLACEHOLDER_DATA, null, 2);
